package com.mycompany.muayene.Forms.MainMenu;

import com.mycompany.muayene.Forms.IFrame;
import com.mycompany.muayene.Forms.PreLoadedFrame;
import java.awt.event.ActionEvent;
import javax.swing.JPanel;

/**
 *
 * @author Mustafa
 */
public class DenetimForm extends JPanel implements IFrame {

    /**
     * Creates new form DenetleForm
     */
    public DenetimForm() {
        initComponents();
        geriButton.addActionListener(this::onGeriButtonActionPerformed);
        doktorlarButton.addActionListener(this::onDoktorlarButtonActionPerformed);
        hastalarButton.addActionListener(this::onHastalarButtonActionPerformed);
        testVerileriYukleButton.addActionListener(this::onTestverileriYukleButtonActionPerformed);
        recetelerButton.addActionListener(this::onRecetelerButtonActionPerformed);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        doktorlarButton = new javax.swing.JButton();
        testVerileriYukleButton = new javax.swing.JButton();
        hastalarButton = new javax.swing.JButton();
        recetelerButton = new javax.swing.JButton();
        geriButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Denetim Paneli");

        doktorlarButton.setText("Doktorlar");

        testVerileriYukleButton.setText("Test Verilerini Yükle");

        hastalarButton.setText("Kayıtlı Hastalar");

        recetelerButton.setText("Reçeteler");

        geriButton.setText("Geri");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(testVerileriYukleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(doktorlarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hastalarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recetelerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(geriButton)
                    .addContainerGap()))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doktorlarButton)
                    .addComponent(hastalarButton))
                .addGap(31, 31, 31)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testVerileriYukleButton)
                    .addComponent(recetelerButton))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLayout.createSequentialGroup()
                    .addContainerGap(358, Short.MAX_VALUE)
                    .addComponent(geriButton)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public JPanel getPanel() {
        return panel;
    }

    @Override
    public void update() {
        IFrame.super.update(); //To change body of generated methods, choose Tools | Templates.
    }

    public void onGeriButtonActionPerformed(ActionEvent e) {
        PreLoadedFrame.DENETIM_FRAME.setVisibility(false);
        PreLoadedFrame.HBYS_FRAME.setVisibility(true);
    }

    public void onDoktorlarButtonActionPerformed(ActionEvent e) {
        PreLoadedFrame.DENETIM_FRAME.setVisibility(false);
        PreLoadedFrame.DOKTORLAR_FRAME.setVisibility(true);
    }

    public void onHastalarButtonActionPerformed(ActionEvent e) {
        PreLoadedFrame.DENETIM_FRAME.setVisibility(false);
        PreLoadedFrame.HASTALAR_FRAME.setVisibility(true);
    }

    public void onTestverileriYukleButtonActionPerformed(ActionEvent e) {
        // TODO: test verilerini yukleyen bir query gir
    }

    public void onRecetelerButtonActionPerformed(ActionEvent e) {
        PreLoadedFrame.DENETIM_FRAME.setVisibility(false);
        PreLoadedFrame.RECETELER_FRAME.setVisibility(true);
    }

    @Override
    public String getTitle(){ return "Denetim Menüsü"; }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doktorlarButton;
    private javax.swing.JButton geriButton;
    private javax.swing.JButton hastalarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel;
    private javax.swing.JButton recetelerButton;
    private javax.swing.JButton testVerileriYukleButton;
    // End of variables declaration//GEN-END:variables
}
