package com.mycompany.muayene.Forms.MainMenu;

import com.mycompany.muayene.Forms.IFrame;
import com.mycompany.muayene.Forms.PreLoadedFrame;
import com.mycompany.muayene.Model.Ilac;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;

/**
 *
 * @author Mustafa
 */
public class IlaclarForm extends JPanel implements IFrame {

    
    private List<Ilac> ilacList;
    /**
     * Creates new form IlaclarForm
     */
    public IlaclarForm() {
        initComponents();
        ilacJList.addListSelectionListener(this::onIlacJListValueChanged);
        geriButton.addActionListener(this::onGeriButtonActionPerformed);
        cikarButton.addActionListener(this::onCikarButtonActionPerformed);
        ekleButton.addActionListener(this::onEkleButtonActionPerformed);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ilacJList = new javax.swing.JList<>();
        geriButton = new javax.swing.JButton();
        entryField = new javax.swing.JTextField();
        ekleButton = new javax.swing.JButton();
        cikarButton = new javax.swing.JButton();

        jScrollPane1.setViewportView(ilacJList);

        geriButton.setText("Geri");

        ekleButton.setText("Ekle");

        cikarButton.setText("Çıkar");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(geriButton))
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(entryField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ekleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cikarButton)
                .addGap(14, 14, 14))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entryField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ekleButton)
                    .addComponent(cikarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(geriButton))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public JPanel getPanel() {
        return this.panel;
    }

    public void update() {
        ilacList = Ilac.read();
        updateFromList();
    }
    private void updateFromList() {
        String[] ilaclarString = new String[ilacList.size()];
        for (int i = 0; i < ilacList.size(); i++) {
            ilaclarString[i] = ilacList.get(i).getIlacAdi();
        }
        ilacJList.setListData(ilaclarString);
    }

    private void onEkleButtonActionPerformed(ActionEvent actionEvent) {
        String ilacAdi = entryField.getText();
        if (ilacAdi.isEmpty()) return;
        Ilac ilac = getIlacFromIlacName(ilacAdi);
        if (ilac != null) return;
        ilac = new Ilac(ilacAdi);
        Ilac.create(ilac);
        ilacList.add(ilac);
        updateFromList();
        entryField.setText("");
    }

    private void onCikarButtonActionPerformed(ActionEvent actionEvent) {
        String ilacAdi = entryField.getText();
        if (ilacAdi.isEmpty()) return;
        Ilac ilac = getIlacFromIlacName(ilacAdi);
        if (ilac == null) return;
        Ilac.delete(ilac);
        ilacList.remove(ilac);
        updateFromList();
        entryField.setText("");
    }

    private void onIlacJListValueChanged(ListSelectionEvent e) {
        if (ilacJList.getSelectedValue() == null) return;
        entryField.setText(ilacJList.getSelectedValue().toString());
    }

    private void onGeriButtonActionPerformed(ActionEvent actionEvent) {
        PreLoadedFrame.ILACLAR_FRAME.setVisibility(false);
        PreLoadedFrame.HBYS_FRAME.setVisibility(true);
    }
    private Ilac getIlacFromIlacName(String ilacName) {
        for (Ilac ilac : ilacList) {
            if (ilac.getIlacAdi().equals(ilacName)) return ilac;
        }
        return null;
    }

    @Override
    public String getTitle(){ return "İlaçlar Menüsü"; }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cikarButton;
    private javax.swing.JButton ekleButton;
    private javax.swing.JTextField entryField;
    private javax.swing.JButton geriButton;
    private javax.swing.JList<String> ilacJList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
