package com.mycompany.muayene.Forms;

import java.awt.event.ActionEvent;
import javax.swing.JPanel;

/**
 *
 * @author Mustafa
 */
public class HBYSForm extends JPanel implements IFrame {

    /**
     * Creates new form HBYSForm
     */
    public HBYSForm() {
        initComponents();
        muayeneButton.addActionListener(this::onMuayeneButtonActionPerformed);
        denetleButton.addActionListener(this::onDenetleButtonActionPerformed);
        ilaclarButton.addActionListener(this::onIlaclarButtonActionPerformed);
        cikisButton.addActionListener(this::onCikisButtonActionPerformed);
    }
    
    @Override
    public JPanel getPanel() {
        return this.panel;
    }

    public void onMuayeneButtonActionPerformed(ActionEvent actionEvent) {
        PreLoadedFrame.HBYS_FRAME.setVisibility(false);
        PreLoadedFrame.MUAYENE_FRAME.setVisibility(true);
    }
    public void onDenetleButtonActionPerformed(ActionEvent actionEvent) {
        PreLoadedFrame.HBYS_FRAME.setVisibility(false);
        PreLoadedFrame.DENETIM_FRAME.setVisibility(true);
    }
    public void onIlaclarButtonActionPerformed(ActionEvent actionEvent) {
        PreLoadedFrame.HBYS_FRAME.setVisibility(false);
        PreLoadedFrame.ILACLAR_FRAME.setVisibility(true);
    }
    public void onCikisButtonActionPerformed(ActionEvent actionEvent) {
        System.exit(1);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        muayeneButton = new javax.swing.JButton();
        denetleButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ilaclarButton = new javax.swing.JButton();
        cikisButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(520, 400));

        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 80, 10);
        flowLayout2.setAlignOnBaseline(true);
        jPanel1.setLayout(flowLayout2);

        muayeneButton.setText("Muayene");
        jPanel1.add(muayeneButton);

        denetleButton.setText("Denetle");
        denetleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denetleButtonActionPerformed(evt);
            }
        });
        jPanel1.add(denetleButton);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HBYS");

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 80, 10);
        flowLayout1.setAlignOnBaseline(true);
        jPanel2.setLayout(flowLayout1);

        ilaclarButton.setText("İlaçlar");
        jPanel2.add(ilaclarButton);

        cikisButton.setText("Çıkış");
        jPanel2.add(cikisButton);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void denetleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denetleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_denetleButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cikisButton;
    private javax.swing.JButton denetleButton;
    private javax.swing.JButton ilaclarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton muayeneButton;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables

}
