package com.mycompany.muayene.Forms.MainMenu.MuayeneMenu;

import com.mycompany.muayene.Forms.IFrame;
import com.mycompany.muayene.Forms.PreLoadedFrame;
import com.mycompany.muayene.Model.Hasta;
import java.awt.event.ActionEvent;
import javax.swing.JPanel;

/**
 *
 * @author Mustafa
 */
public class HastaOlusturForm extends JPanel implements IFrame {

    /**
     * Creates new form HastaOlusturForm
     */
    public HastaOlusturForm() {
        initComponents();
        geriButton.addActionListener(this::onGeriButtonActionPerformed);
        kaydetButton.addActionListener(this::onKaydetButtonActionPerformed);
        sifirlaButton.addActionListener(this::onSifirlaButtonActionPerformed);
    }
    
    private void clearFields() {
        adField.setText("");
        soyadField.setText("");
        tcField.setText("");
    }




    private void onGeriButtonActionPerformed(ActionEvent actionEvent) {
        HastaOlusturForm.clearHasta();
        PreLoadedFrame.HASTA_OLUSTUR_FRAME.setVisibility(false);
        PreLoadedFrame.MUAYENE_FRAME.setVisibility(true);
    }

    private void onSifirlaButtonActionPerformed(ActionEvent actionEvent) {
        clearFields();
    }
    private void onKaydetButtonActionPerformed(ActionEvent actionEvent) {
        if (adField.getText().isEmpty() || soyadField.getText().isEmpty() || tcField.getText().isEmpty()) {
            savedStatusAnimation("Lütfen tüm alanları doldurunuz.");
            return;
        }
        if (tcField.getText().length() != 11) {
            savedStatusAnimation("TCKN 11 haneli olmalıdır.");
            return;
        }
        for (char c : tcField.getText().toCharArray()) {
            if (!Character.isDigit(c)) {
                savedStatusAnimation("TCKN rakamlardan oluşmalıdır.");
                return;
            }
        }
        HastaOlusturForm.hasta = new Hasta(adField.getText(), soyadField.getText(), Long.parseLong(tcField.getText()), null, null);
        PreLoadedFrame.HASTA_OLUSTUR_FRAME.setVisibility(false);
        PreLoadedFrame.MUAYENE_FRAME.setVisibility(true);
    }

    private void savedStatusAnimation(String resultMessage) {
        new Thread(() -> {
            statusField.setText(resultMessage);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            statusField.setText("");
        }).start();
    }

    @Override
    public String getTitle(){ return "Hasta Girişi"; }

    //Static field
    private static Hasta hasta = null;
    public static Hasta getHasta(){
        return hasta;
    }
    public static void clearHasta() {
        hasta = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        adField = new javax.swing.JTextField();
        soyadField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tcField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sifirlaButton = new javax.swing.JButton();
        geriButton = new javax.swing.JButton();
        kaydetButton = new javax.swing.JButton();
        statusField = new javax.swing.JLabel();

        jLabel1.setText("Ad");

        jLabel2.setText("Soyad");

        jLabel3.setText("TCKN");

        sifirlaButton.setText("Sıfırla");

        geriButton.setText("Geri");

        kaydetButton.setText("Kaydet");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tcField))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adField)
                                    .addComponent(soyadField)))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sifirlaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kaydetButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(geriButton)
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(adField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(soyadField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tcField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 246, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(geriButton)
                        .addComponent(sifirlaButton)
                        .addComponent(kaydetButton))
                    .addComponent(statusField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public JPanel getPanel() {
        return this.panel;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adField;
    private javax.swing.JButton geriButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton kaydetButton;
    private javax.swing.JPanel panel;
    private javax.swing.JButton sifirlaButton;
    private javax.swing.JTextField soyadField;
    private javax.swing.JLabel statusField;
    private javax.swing.JTextField tcField;
    // End of variables declaration//GEN-END:variables
}
