package com.mycompany.muayene.Forms.MainMenu.MuayeneMenu;

import com.mycompany.muayene.Forms.IFrame;
import com.mycompany.muayene.Forms.PreLoadedFrame;
import com.mycompany.muayene.Model.Ilac;
import com.mycompany.muayene.Model.Recete;
import java.awt.event.ActionEvent;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;

/**
 *
 * @author Mustafa
 */
public class ReceteOlusturForm extends javax.swing.JPanel implements IFrame {

    private List<String> yazilanIlacStrList = new ArrayList<>();
    /**
     * Creates new form ReceteOlusturForm
     */
    public ReceteOlusturForm() {
        initComponents();
        ilacJList.addListSelectionListener(this::onIlacListValueChanged);
        geriButton.addActionListener(this::onGeriButtonActionPerformed);
        kaydetButton.addActionListener(this::onKaydetButtonActionPerformed);
        sifirlaButton.addActionListener(this::onSifirlaButtonActionPerformed);
        cikarButton.addActionListener(this::onCikarButtonActionPerformed);
        ekleButton.addActionListener(this::onEkleButtonActionPerformed);
    }




    

    @Override
    public void update() {
        updateIlacBox();
    }

    private void updateIlacBox() {
        jIlaclarBox.removeAllItems();
        for (Ilac ilac : Ilac.read()) {
            jIlaclarBox.addItem(ilac.getIlacAdi());
        }
    }



    private void updateReceteIlacList() {
        ilacJList.setListData(yazilanIlacStrList.toArray());
    }


    private void onEkleButtonActionPerformed(ActionEvent actionEvent) {
        String ilacAdi = jIlaclarBox.getSelectedItem().toString();
        if (ilacAdi.isEmpty()) return;
        yazilanIlacStrList.add(ilacAdi);
        updateReceteIlacList();
    }
    private void onCikarButtonActionPerformed(ActionEvent actionEvent) {
        String ilacAdi = (String) jIlaclarBox.getSelectedItem();
        removeIlacFromIlacName(ilacAdi);
        updateReceteIlacList();
    }

    private void onIlacListValueChanged(ListSelectionEvent e) {
        if (ilacJList.getSelectedValue() == null) return;
        String ilacAdi = (String) ilacJList.getSelectedValue();
        jIlaclarBox.setSelectedItem(ilacAdi);
    }

    private void onGeriButtonActionPerformed(ActionEvent actionEvent) {
        ReceteOlusturForm.clearRecete();
        PreLoadedFrame.RECETE_OLUSTUR_FRAME.setVisibility(false);
        PreLoadedFrame.MUAYENE_FRAME.setVisibility(true);
    }

    private void onSifirlaButtonActionPerformed(ActionEvent actionEvent) {
        yazilanIlacStrList.clear();
        updateReceteIlacList();
    }
    private void onKaydetButtonActionPerformed(ActionEvent actionEvent) {
        List<Ilac> ilaclar = new ArrayList<>();
        yazilanIlacStrList.forEach(ilacAdi -> { ilaclar.add(new Ilac(ilacAdi));});
        ReceteOlusturForm.recete = new Recete(new Timestamp(System.currentTimeMillis()), ilaclar);
        PreLoadedFrame.RECETE_OLUSTUR_FRAME.setVisibility(false);
        PreLoadedFrame.MUAYENE_FRAME.setVisibility(true);
    }

    private void removeIlacFromIlacName(String ilacName) {
        int indexToRemove = -1;
        for (int i = 0; i < yazilanIlacStrList.size(); i++) {
            String yazilanIlacStr = yazilanIlacStrList.get(i);
            if (ilacName.equals(yazilanIlacStr)) {
                indexToRemove = i;
                break;
            }
        }
        if (indexToRemove != -1) yazilanIlacStrList.remove(indexToRemove);
    }


    @Override
    public String getTitle(){ return "Reçete Girişi"; }

    //Static field

    private static Recete recete = null;

    public static void clearRecete() {
        recete = null;
    }

    public static Recete getRecete() {
        return recete;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jIlaclarBox = new javax.swing.JComboBox<>();
        ekleButton = new javax.swing.JButton();
        cikarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ilacJList = new javax.swing.JList<>();
        sifirlaButton = new javax.swing.JButton();
        geriButton = new javax.swing.JButton();
        kaydetButton = new javax.swing.JButton();

        ekleButton.setText("Ekle");

        cikarButton.setText("Çıkar");

        jScrollPane1.setViewportView(ilacJList);

        sifirlaButton.setText("Sıfırla");

        geriButton.setText("Geri");

        kaydetButton.setText("Kaydet");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jIlaclarBox, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ekleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cikarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(sifirlaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kaydetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(geriButton)))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jIlaclarBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ekleButton)
                    .addComponent(cikarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sifirlaButton)
                    .addComponent(geriButton)
                    .addComponent(kaydetButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public JPanel getPanel() {
        return this.panel;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cikarButton;
    private javax.swing.JButton ekleButton;
    private javax.swing.JButton geriButton;
    private javax.swing.JList<Object> ilacJList;
    private javax.swing.JComboBox<String> jIlaclarBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kaydetButton;
    private javax.swing.JPanel panel;
    private javax.swing.JButton sifirlaButton;
    // End of variables declaration//GEN-END:variables
}
