package com.mycompany.muayene.Forms.MainMenu.DenetimMenu;

import com.mycompany.muayene.Forms.IFrame;
import com.mycompany.muayene.Forms.PreLoadedFrame;
import com.mycompany.muayene.Model.Doktor;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;

/**
 *
 * @author Mustafa
 */
public class DoktorlarForm extends JPanel implements IFrame {

    private List<Doktor> doktorList = new ArrayList<>();

    /**
     * Creates new form DoktorlarForm
     */
    public DoktorlarForm() {
        initComponents();
        geriButton.addActionListener(this::onGeriButtonActionPerformed);
        ekleButton.addActionListener(this::onEkleButtonActionPerformed);
        cikarButton.addActionListener(this::onCikarButtonActionPerformed);
        doktorJList.addListSelectionListener(this::onDoktorJListValueChanged);
    }

    @Override
    public void update() {
        doktorList = Doktor.read();
        updateFromList();
    }

    private void updateFromList() {
        String[] doktorlarString = new String[doktorList.size()];
        for (int i = 0; i < doktorList.size(); i++) {
            Doktor doktor = doktorList.get(i);
            doktorlarString[i] = doktor.getAd() + " " + doktor.getSoyad() + " SN:" + doktor.getSicilNo();
        }
        doktorJList.setListData(doktorlarString);
    }

    @Override
    public String getTitle() {
        return "Doktorlar";
    }

    private void onGeriButtonActionPerformed(ActionEvent e) {
        PreLoadedFrame.DOKTORLAR_FRAME.setVisibility(false);
        PreLoadedFrame.DENETIM_FRAME.setVisibility(true);
    }

    private void onEkleButtonActionPerformed(ActionEvent actionEvent) {
        String ad = adField.getText();
        String soyad = soyadField.getText();
        String tckn = tcknField.getText();
        if (tckn.length() != 11) {
            savedStatusAnimation("TCKN 11 haneli olmalıdır.");
            return;
        }
        for (char c : tckn.toCharArray()) {
            if (!Character.isDigit(c)) {
                savedStatusAnimation("TCKN rakamlardan oluşmalıdır.");
                return;
            }
        }
        String sicilNo = sicilNoField.getText();
        if (ad.isEmpty() || soyad.isEmpty() || tckn.isEmpty() || sicilNo.isEmpty()) {
            savedStatusAnimation("Lütfen tüm alanları doldurun.");
            return;
        }
        Doktor doktor = getDoktorFromSicilNo(sicilNo);
        if (doktor != null) {
            savedStatusAnimation("Bu sicil numarası zaten mevcut.");
            return;
        }
        doktor = new Doktor(ad, soyad, Long.parseLong(tckn), sicilNo);
        Doktor.create(doktor);
        doktorList.add(doktor);
        updateFromList();
        adField.setText("");
        soyadField.setText("");
        tcknField.setText("");
        sicilNoField.setText("");
        savedStatusAnimation("Doktor eklendi");
    }

    private void onCikarButtonActionPerformed(ActionEvent actionEvent) {
        String sicilNo = sicilNoField.getText();
        if (sicilNo.isEmpty()) {
            savedStatusAnimation("Lütfen sicil numarasını girin.");
            return;
        }
        Doktor doktor = getDoktorFromSicilNo(sicilNo);
        Doktor.delete(doktor);
        doktorList.remove(doktor);
        updateFromList();
        savedStatusAnimation("Doktor silindi");
    }

    private void onDoktorJListValueChanged(ListSelectionEvent e) {
        if (doktorJList.getSelectedValue() == null) {
            return;
        }
        String sicilNo = doktorJList.getSelectedValue().toString().split(" SN:")[1];
        Doktor doktor = getDoktorFromSicilNo(sicilNo);
        if (doktor == null) {
            return;
        }
        adField.setText(doktor.getAd());
        soyadField.setText(doktor.getSoyad());
        tcknField.setText(doktor.getTcKimlikNo() + "");
        sicilNoField.setText(doktor.getSicilNo());
    }

    private Doktor getDoktorFromSicilNo(String sicilNo) {
        for (Doktor doktor : doktorList) {
            if (doktor.getSicilNo().equals(sicilNo)) {
                return doktor;
            }
        }
        return null;
    }

    private void savedStatusAnimation(String resultMessage) {
        new Thread(() -> {
            statusField.setText(resultMessage);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            statusField.setText("");
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adField = new javax.swing.JTextField();
        soyadField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tcknField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sicilNoField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        doktorJList = new javax.swing.JList<>();
        geriButton = new javax.swing.JButton();
        statusField = new javax.swing.JLabel();
        ekleButton = new javax.swing.JButton();
        cikarButton = new javax.swing.JButton();

        jLabel1.setText("Ad");

        jLabel2.setText("Soyad");

        jLabel3.setText("TCKN");

        jLabel4.setText("Sicil No");

        jScrollPane1.setViewportView(doktorJList);

        geriButton.setText("Geri");

        ekleButton.setText("Ekle");

        cikarButton.setText("Çıkar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(adField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(soyadField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(statusField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(geriButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ekleButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(tcknField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(sicilNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cikarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soyadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tcknField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sicilNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ekleButton)
                    .addComponent(cikarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(geriButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(statusField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public JPanel getPanel() {
        return this.jPanel1;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adField;
    private javax.swing.JButton cikarButton;
    private javax.swing.JList<String> doktorJList;
    private javax.swing.JButton ekleButton;
    private javax.swing.JButton geriButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField sicilNoField;
    private javax.swing.JTextField soyadField;
    private javax.swing.JLabel statusField;
    private javax.swing.JTextField tcknField;
    // End of variables declaration//GEN-END:variables
}
